// <auto-generated />
using Centurion.WebhookSender.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Centurion.WebhookSender.Infrastructure.Migrations
{
    [DbContext(typeof(WebhooksContext))]
    [Migration("20210718180706_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Centurion.Contracts.WebhookSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("FailureUrl")
                        .HasColumnType("text")
                        .HasColumnName("failure_url");

                    b.Property<string>("SuccessUrl")
                        .HasColumnType("text")
                        .HasColumnName("success_url");

                    b.HasKey("UserId")
                        .HasName("pk_webhook_settings");

                    b.ToTable("webhook_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
