@startuml
'https://plantuml.com/class-diagram

class ExecutionSchedule {
  ScheduleStartContainers();
  ScheduleStopContainers();

  ScheduleStartNewNodes();
  ScheduleShutdown();
}

@enduml
