// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package monitor

import (
	context "context"
	integration "github.com/CenturionLabs/centurion/checkout-service/contracts/monitor/integration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorClient interface {
	WatchStreamed(ctx context.Context, in *WatchCommand, opts ...grpc.CallOption) (Monitor_WatchStreamedClient, error)
}

type monitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorClient(cc grpc.ClientConnInterface) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) WatchStreamed(ctx context.Context, in *WatchCommand, opts ...grpc.CallOption) (Monitor_WatchStreamedClient, error) {
	stream, err := c.cc.NewStream(ctx, &Monitor_ServiceDesc.Streams[0], "/monitor.Monitor/WatchStreamed", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorWatchStreamedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Monitor_WatchStreamedClient interface {
	Recv() (*integration.MonitoringStatusChanged, error)
	grpc.ClientStream
}

type monitorWatchStreamedClient struct {
	grpc.ClientStream
}

func (x *monitorWatchStreamedClient) Recv() (*integration.MonitoringStatusChanged, error) {
	m := new(integration.MonitoringStatusChanged)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorServer is the server API for Monitor service.
// All implementations must embed UnimplementedMonitorServer
// for forward compatibility
type MonitorServer interface {
	WatchStreamed(*WatchCommand, Monitor_WatchStreamedServer) error
	mustEmbedUnimplementedMonitorServer()
}

// UnimplementedMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (UnimplementedMonitorServer) WatchStreamed(*WatchCommand, Monitor_WatchStreamedServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStreamed not implemented")
}
func (UnimplementedMonitorServer) mustEmbedUnimplementedMonitorServer() {}

// UnsafeMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServer will
// result in compilation errors.
type UnsafeMonitorServer interface {
	mustEmbedUnimplementedMonitorServer()
}

func RegisterMonitorServer(s grpc.ServiceRegistrar, srv MonitorServer) {
	s.RegisterService(&Monitor_ServiceDesc, srv)
}

func _Monitor_WatchStreamed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorServer).WatchStreamed(m, &monitorWatchStreamedServer{stream})
}

type Monitor_WatchStreamedServer interface {
	Send(*integration.MonitoringStatusChanged) error
	grpc.ServerStream
}

type monitorWatchStreamedServer struct {
	grpc.ServerStream
}

func (x *monitorWatchStreamedServer) Send(m *integration.MonitoringStatusChanged) error {
	return x.ServerStream.SendMsg(m)
}

// Monitor_ServiceDesc is the grpc.ServiceDesc for Monitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStreamed",
			Handler:       _Monitor_WatchStreamed_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitor/monitor_service.proto",
}
