version: "2.2"

services:
  cloudmanagerdb:
    image: postgres:13
    volumes:
      - ./data/cloudmanager/psql/data:/var/lib/postgresql/data
      - ./data/cloudmanager/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: cloudmanager
      POSTGRES_PASSWORD: cloudmanager
      POSTGRES_DB: cloudmanager
    ports:
      - 45432:5432

  taskmanagerdb:
    image: postgres:13
    volumes:
      - ./data/taskmanager/psql/data:/var/lib/postgresql/data
      - ./data/taskmanager/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager
    ports:
      - 15432:5432

  accountsdb:
    image: postgres:13
    volumes:
      - ./data/accounts/psql/data:/var/lib/postgresql/data
      - ./data/accounts/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
      POSTGRES_DB: accounts
    ports:
      - 25432:5432

  webhooksdb:
    image: postgres:13
    volumes:
      - ./data/webhooks/psql/data:/var/lib/postgresql/data
      - ./data/webhooks/psql/dumps:/db_dumps
    environment:
      POSTGRES_USER: webhooks
      POSTGRES_PASSWORD: webhooks
      POSTGRES_DB: webhooks
    ports:
      - 35432:5432

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rmq
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - ./data/shared/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rmq
      - ./data/shared/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6
    command: [ "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./data/shared/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - 6379:6379