// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: checkout/crypto.proto

package checkout

import (
	contracts "github.com/CenturionLabs/centurion/checkout-service/contracts"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encrypted string `protobuf:"bytes,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
}

func (x *EncryptionResult) Reset() {
	*x = EncryptionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_crypto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionResult) ProtoMessage() {}

func (x *EncryptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_crypto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionResult.ProtoReflect.Descriptor instead.
func (*EncryptionResult) Descriptor() ([]byte, []int) {
	return file_checkout_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptionResult) GetEncrypted() string {
	if x != nil {
		return x.Encrypted
	}
	return ""
}

var File_checkout_crypto_proto protoreflect.FileDescriptor

var file_checkout_crypto_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x30, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x32, 0x3d, 0x0a, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x33, 0x0a, 0x07,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1a, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x7e, 0x0a, 0x15, 0x67, 0x67, 0x2e, 0x63, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x69, 0x6f,
	0x6e, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x69, 0x6f, 0x6e,
	0x4c, 0x61, 0x62, 0x73, 0x2f, 0x63, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x69, 0x6f, 0x6e, 0x2f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0xaa, 0x02, 0x1c, 0x43, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkout_crypto_proto_rawDescOnce sync.Once
	file_checkout_crypto_proto_rawDescData = file_checkout_crypto_proto_rawDesc
)

func file_checkout_crypto_proto_rawDescGZIP() []byte {
	file_checkout_crypto_proto_rawDescOnce.Do(func() {
		file_checkout_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkout_crypto_proto_rawDescData)
	})
	return file_checkout_crypto_proto_rawDescData
}

var file_checkout_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_checkout_crypto_proto_goTypes = []interface{}{
	(*EncryptionResult)(nil),      // 0: checkout.EncryptionResult
	(*contracts.ProfileData)(nil), // 1: ProfileData
}
var file_checkout_crypto_proto_depIdxs = []int32{
	1, // 0: checkout.Crypto.Encrypt:input_type -> ProfileData
	0, // 1: checkout.Crypto.Encrypt:output_type -> checkout.EncryptionResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checkout_crypto_proto_init() }
func file_checkout_crypto_proto_init() {
	if File_checkout_crypto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkout_crypto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkout_crypto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_crypto_proto_goTypes,
		DependencyIndexes: file_checkout_crypto_proto_depIdxs,
		MessageInfos:      file_checkout_crypto_proto_msgTypes,
	}.Build()
	File_checkout_crypto_proto = out.File
	file_checkout_crypto_proto_rawDesc = nil
	file_checkout_crypto_proto_goTypes = nil
	file_checkout_crypto_proto_depIdxs = nil
}
